# Site Settings
title: Dmitry Mardukhayev 
email: dmitrymar@yahoo.com 
description: >
  Dmitry Mardukhayev Web Developer.
baseurl: ""
url: "https://dmitrymar.github.io/"
twitter_username: dmitrymar 
github_username:  dmitrymar 
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM